version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    networks:
      - mern-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/SampleApp
      - NODE_ENV=production
    networks:
      - mern-network
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  selenium-tests:
    build: ./selenium-tests
    networks:
      - mern-network
    depends_on:
      - frontend
      - backend
    environment:
      - APP_URL=http://frontend

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data: